test-result-reporting-client update RUSTSEC deps (#5002)
Updates dependencies that violate RUSTSEC

<details>
<summary>Cargo Audit</summary>

```
    Scanning Cargo.lock for vulnerabilities (79 crate dependencies)
Crate:         hyper
Version:       0.13.9
Title:         Multiple Transfer-Encoding headers misinterprets request payload
Date:          2021-02-05
ID:            RUSTSEC-2021-0020
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0020
Solution:      Upgrade to >=0.14.3 OR >=0.13.10, <0.14.0 OR >=0.12.36, <0.13.0
Dependency tree:
hyper 0.13.9
└── trc-client 0.1.0

Crate:         net2
Version:       0.2.37
Warning:       unmaintained
Title:         `net2` crate has been deprecated; use `socket2` instead
Date:          2020-05-01
ID:            RUSTSEC-2020-0016
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0016
Dependency tree:
net2 0.2.37
├── miow 0.2.2
│   └── mio 0.6.23
│       └── tokio 0.2.24
│           ├── tokio-util 0.3.1
│           │   └── h2 0.2.7
│           │       └── hyper 0.13.9
│           │           └── trc-client 0.1.0
│           ├── hyper 0.13.9
│           └── h2 0.2.7
└── mio 0.6.23

Crate:         pin-project-lite
Version:       0.1.11
Warning:       yanked
Dependency tree:
pin-project-lite 0.1.11

Crate:         pin-project-lite
Version:       0.2.4
Warning:       yanked
Dependency tree:
pin-project-lite 0.2.4

error: 1 vulnerability found!
warning: 3 allowed warnings found
```
</details>