check_submodules update RUSTSEC deps (#5001)
Updates lock file with deps that do not have security issues

<details>
<summary> Cargo Audit </summary>

```
Crate:         smallvec
Version:       0.6.12
Title:         Buffer overflow in SmallVec::insert_many
Date:          2021-01-08
ID:            RUSTSEC-2021-0003
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0003
Solution:      Upgrade to >=0.6.14, <1.0.0 OR >=1.6.1
Dependency tree:
smallvec 0.6.12
└── unicode-normalization 0.1.8
    └── idna 0.1.5
        └── url 1.7.2
            └── git2 0.7.5
                └── check_submodules 0.1.1

Crate:         failure
Version:       0.1.6
Warning:       unmaintained
Title:         failure is officially deprecated/unmaintained
Date:          2020-05-02
ID:            RUSTSEC-2020-0036
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree:
failure 0.1.6
├── edgelet-utils 0.1.0
│   └── check_submodules 0.1.1
└── check_submodules 0.1.1

Crate:         quote
Version:       1.0.2
Warning:       yanked
Dependency tree:
quote 1.0.2
├── synstructure 0.12.1
│   └── failure_derive 0.1.6
│       └── failure 0.1.6
│           ├── edgelet-utils 0.1.0
│           │   └── check_submodules 0.1.1
│           └── check_submodules 0.1.1
├── syn 1.0.7
│   ├── synstructure 0.12.1
│   └── failure_derive 0.1.6
└── failure_derive 0.1.6

error: 1 vulnerability found!
warning: 2 allowed warnings found
```
</details>