[mqtt] Format error on exit from main (#2683)
Old output: 

```
Mar 11 13:35:50.878  INFO mqtt_broker::broker: broker is shutdown.
Error: Error { inner: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

An error occurred binding the server's listening socket. }
```

New output:

```
Mar 11 11:47:13.496  INFO mqtt_broker::broker: broker is shutdown.
Error: An error occurred binding the server's listening socket.
        caused by: Permission denied (os error 13)
```