Enable Rust Coverage for Release 1.1 Branch (#5641)
1. Enable Code Coverage for Rust Code with 62% Check in Gate
2.  Disable one of the test from running during code coverage test runs. Fails with  cryptic error. Investigate Later
Error Due to 
(---- run_ctest stdout ----
Start Running ctest for HSM library
thread 'run_ctest' panicked at 'Did not find OUT_DIR in build environment: NotPresent', hsm-sys/tests/hsm_ctest.rs:17:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    run_ctest

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out)